### ISSUE TITLE
Cant change user organization role through terraform

### ISSUE THREAD

**Issue by KarolGongola** [astronomer/terraform-provider-astro#149]
### Description

When I have created user via astro_user_invite resource, I cant modify user organization role via terraform.
Create user resource like that:
```
resource "astro_user_invite" "karol_gongola" {
  email = "karol.gongola@DOMAIN.COM"
  role  = "ORGANIZATION_OWNER"
}
```
Try to change it
```
resource "astro_user_invite" "karol_gongola" {
  email = "karol.gongola@DOMAIN.COM"
  role  = "ORGANIZATION_MEMBER"
}
```
then `terraform apply`  returns:
```
│ Error: Client error
│
│   with astro_user_invite.karol_gongola,
│   on main.tf line 142, in resource "astro_user_invite" "karol_gongola":
│  142: resource "astro_user_invite" "karol_gongola" {
│
│ Invalid request: Invitee has existing role in organization XYZ, status: 400, requestId: ZYX
```
Is there any other way to change user role via terraform?

### Acceptance Criteria

- possibility to modify user organization role via terraform added

**Comment by ichung08** [comment]
Hey @KarolGongola 

The `user_invite` resource is only to add a user to an organization.

To modify a user's role you can use the [`user_roles` resource](https://registry.terraform.io/providers/astronomer/astro/latest/docs/resources/user_roles) as long as you have the user's `userId`.

**Comment by KarolGongola** [comment]
You are right. I havent realised it. Thank you.
