### ISSUE TITLE
[Bug]: V1.0.0 is not working. resources flag provided but not defined

### ISSUE THREAD

**Issue by vishakseshadri** [astronomer/terraform-provider-astro#154]
### Description

`./terraform-provider-astro_v1.0.0 -
resources workspace,deployment,cluster,api-token,team,team_roles,user_roles -organizationId <org_id> -runTerraformInit
flag provided but not defined: -resources
Usage of ./terraform-provider-astro_v1.0.0:
  -debug
    	set to true to run the provider with support for debuggers like delve`

Looks like the new version is not properly implemented. Further, with version 0.1.3, it is limited to 20 resources per type instead of all the resources defined in the current environment.

### Steps To Reproduce

With version 0.1.3, download the script and run it - (replace orgID with your organization ID )
`./terraform-provider-astro-import-script_v0.1.3_darwin_arm64 -resources workspace,deployment,cluster,api_token,team,team_roles,user_roles -organizationId <orgID> -runTerraformInit`

This works fine, but only downloads 20 resources per type. Looks like the tool has not implemented handling pagination of API results.

**Comment by ichung08** [comment]
Hey @vishakseshadri thanks for bringing this up, I will look into handling pagination of API results in the script. The latest version of the import script is v0.1.3.
