### ISSUE TITLE
The provider astronomer/astro does not support resource type "astro_user_invite"

### ISSUE THREAD

**Issue by Poornima030596** [astronomer/terraform-provider-astro#163]
I  am using HCL and not Golang.Is there the same functions available using HCL ?

user invite isn't supported .

provider used :
terraform {
  required_providers {
    astro = {
      source  = "astronomer/astro"
      version = "0.3.0"
    }
  }
}

provider "astro" {
  organization_id = ""
}

**Comment by ichung08** [comment]
The resource `astro_user_invite` is not supported on the version `0.3.0`. You'll need to upgrade to `1.0.0` to use that resource. You can do simply by changing the version used in the provider.
