### ISSUE TITLE
[Bug]: Error: The terraform-provider-astro_v1.0.0.exe plugin crashed!

### ISSUE THREAD

**Issue by Poornima030596** [astronomer/terraform-provider-astro#169]
### Description

Stack trace from the terraform-provider-astro_v1.0.0.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x14fbb6e]

goroutine 73 [running]:
github.com/astronomer/terraform-provider-astro/internal/provider/resources.(*UserRolesResource).Read(0xad0a560, {0x1a42698, 0xab55710}, {{{{0x1a44d48, 0xab762d0}, {0x18051e0, 0xaded600}}, {0x1a45cc0, 0xade1740}}, 0xab496c8, ...}, ...)
        github.com/astronomer/terraform-provider-astro/internal/provider/resources/resource_user_roles.go:195 +0x17e
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xa9168c0, {0x1a42698, 0xab55710}, 0xab55740, 0xa8edb20)
        github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_readresource.go:117 +0x869
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xa9168c0, {0x1a42698, 0xab556c8}, 0xadecac0)
        github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/proto6server/server_readresource.go:55 +0x479
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xa867f40, {0x1a42698, 0xab55428}, 0xa97ab00)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:784 +0x35b
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x18d0b40, 0xa867f40}, {0x1a42698, 0xab55428}, 0xa97aa40, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:482 +0x176
google.golang.org/grpc.(*Server).processUnaryRPC(0xa916780, {0x1a42698, 0xab553f8}, {0x1a452ec, 0xa851400}, 0xac581e0, 0xaa70408, 0x1f9a774, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xf89
google.golang.org/grpc.(*Server).handleStream(0xa916780, {0x1a452ec, 0xa851400}, 0xac581e0)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x1108
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 14
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x13f

Error: The terraform-provider-astro_v1.0.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by ichung08** [comment]
please use the latest import script: https://github.com/astronomer/terraform-provider-astro/releases/tag/import%2Fv0.1.3
